version: '3.8'

services:
  driver:
    build:
      context: ./driver
    command: go run main.go driver --port 8082
    ports:
      - "8082:8082"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./driver:/app

  customer:
    build:
      context: ./customer
    command: go run main.go customer --port 8081
    ports:
      - "8081:8081"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./customer:/app
