version: '3.8'
services:
  driver:
    image: monlaine123/monlai:latest
    command: ["./main", "driver", "--port", "8082"]
    ports:
      - "8082:8082"
    env_file:
      - .env
  customer:
    image: monlaine123/monlai:latest
    command: ["./main", "customer", "--port", "8081"]
    ports:
      - "8081:8081"
    env_file:
      - .env
        EOT
        
        echo "Validating docker-compose.yml"
        docker-compose config || { echo "Invalid docker-compose.yml"; exit 1; }
        
        echo "Pulling latest code"
        if [ ! -d .git ]; then
        echo "Cloning repository"
        git clone ${{ secrets.REPO_URL }} . || { echo "Failed to clone repository"; exit 1; }
        fi
        git fetch origin || { echo "Git fetch failed"; exit 1; }
        git reset --hard origin/main || { echo "Git reset failed"; exit 1; }
        
        echo "Restarting app"
        docker-compose down || { echo "Failed to stop containers"; exit 1; }
        docker-compose pull || { echo "Failed to pull images"; exit 1; }
        docker-compose up --build -d || { echo "Failed to start containers"; exit 1; }
        
        echo "Verifying running containers"
        docker ps || { echo "Failed to list containers"; exit 1; }
        
        echo "Deployment complete"
        EOF