version: '3.8'
services:
  driver:
    image: monlaine123/monlai:latest
    command: ["./main", "driver", "--port", "8082"]
    ports:
      - "8082:8082"
    env_file:
      - .env

  customer:
    image: monlaine123/monlai:latest
    command: ["./main", "customer", "--port", "8081"]
    ports:
      - "8081:8081"
    env_file:
      - .env
